# Generated by Django 3.1.5 on 2021-01-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_device', models.CharField(max_length=50, verbose_name='Type')),
                ('name_of_device', models.CharField(max_length=50, verbose_name='Device name')),
                ('configuration', models.URLField(verbose_name='Link')),
                ('price', models.IntegerField()),
                ('paid_by', models.CharField(max_length=50, verbose_name='Buyer')),
                ('item_number', models.IntegerField()),
                ('db_table', models.CharField(max_length=200, verbose_name='Name of table')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone_number', models.IntegerField(verbose_name='Phone')),
                ('team', models.CharField(max_length=50, verbose_name='Team')),
                ('db_table', models.CharField(max_length=200, verbose_name='Name of table')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(auto_now=True)),
                ('db_table', models.CharField(max_length=200, verbose_name='Name of table')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='staff.device')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff')),
            ],
        ),
    ]
